/**
 * Copyright (C) 2012 Eric Bottard / Guillaume Lederrey (eric.bottard+ghpublic@gmail.com / guillaume.lederrey@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.social.bitbucket.api;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;

/**
 * Describes an OAuth API Consumer.
 *
 * @author Cyprian Śniegota
 * @since 2.0.0
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class BitBucketConsumer {
    /**
     * An identifier assigned by Bitbucket.
     */
    @JsonProperty
    @Getter
    private long id;

    /**
     * Description of this integration. This can be null.
     */
    @JsonProperty
    @Getter
    private String description;

    /**
     * An Oauth key generated by Bitbucket.
     */
    @JsonProperty
    @Getter
    private String key;

    /**
     * Display name for the consumer.
     */
    @JsonProperty
    @Getter
    private String name;

    /**
     * An Oauth secret generated by Bitbucket.
     */
    @JsonProperty
    @Getter
    private String secret;

    /**
     * The URL for the consumer. This can be null.
     */
    @JsonProperty
    @Getter
    private String url;
}
