package org.springframework.social.bitbucket.api;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;

/**
 * Describes a Consumer.
 *
 * @author Cyprian Śniegota
 * @since 2.0.0
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class BitBucketConsumer {
    /**
     * An identifier assigned by Bitbucket.
     */
    @JsonProperty
    @Getter
    private String id;

    /**
     * Description of this integration. This can be null.
     */
    @JsonProperty
    @Getter
    private String description;

    /**
     * An Oauth key generated by Bitbucket.
     */
    @JsonProperty
    @Getter
    private String key;

    /**
     * Display name for the consumer.
     */
    @JsonProperty
    @Getter
    private String name;

    /**
     * An Oauth secret generated by Bitbucket.
     */
    @JsonProperty
    @Getter
    private String secret;

    /**
     * The URL for the consumer. This can be null.
     */
    @JsonProperty
    @Getter
    private String url;
}
